typography_spectrum: 1
color:
  brandColors:
    - '#040707'
    - '#f36c49'
    - '#813927'
    - '#ffffff'
    - '#ff0000'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.86898
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/75f02762-0524-4dbd-a6e9-471ef52e1308.png
name: Bull & Bear News
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f72f4f07-4555-4684-ab7c-fec4a7ddb6e5.png
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: Bull & Bear
purpose: []
