typography_spectrum: 1
color:
  brandColors:
    - '#040707'
    - '#f36c49'
    - '#813927'
    - '#ffffff'
    - '#ff0000'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.86898
analytics:
  google: null
  facebook: null
  twitter: null
name: Bull & Bear
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: Bull & Bear
purpose: []
